name: Build macOS Scheduler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug workspace
        run: |
          echo "Workspace contents:"
          ls -R .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onedir \
            --name scheduler \
            --add-data 'preferences.txt:.' \
            scheduler.py

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: macOS-scheduler
          path: dist/scheduler
